language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
  include:
    - php: 7.2
      env: XDEBUG_OFF="yes"

script:
  - composer update
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - make

after_script:
 - make coveralls
